### PR TITLE
Update Scala version to 2.12.6

### PR DESCRIPTION
**Pull request by hosamaly**

### CODE REVIEW

**Comment by SethTisue** [comment]
I think we probably want to hold off until 2.12.6, since I think language newcomers are especially likely not to understand the implications of being on Java 8 or 9/10, and thus especially likely to be on 9 or 10 just because they're new, and we don't want them bitten by https://github.com/scala/scala-dev/issues/480, which bites even when (for example) doing simple things with ScalaTest

**Comment by hosamaly** [comment]
That makes sense. Thanks.
Would you like me to close the PR?

**Comment by SethTisue** [comment]
@hosamaly 2.12.6 is out, want to update the PR now?

**Comment by hosamaly** [comment]
Done. Thanks!

**Comment by SethTisue** [comment]
you should change the commit comment though :-)

**Comment by hosamaly** [comment]
How embarrassing! Fixed. Thanks.

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
