### PR TITLE
Scala 2.12.8 + ThisBuild slash syntax

### PR DESCRIPTION
**Pull request by eed3si9n**

### CODE REVIEW

**Comment by eed3si9n** [comment]
#2 says "This seed seems to complicated for a minimum sbt project," which I agree, because if people wanted minimum sbt project, you don't need a seed; all you need is `touch build.sbt`, which I demonstrate in [create a minimum sbt build](https://www.scala-sbt.org/1.x/docs/sbt-by-example.html#Create+a+minimum+sbt+build).

The fundamental premise of "sbt new" I think is that copy-pasting build file is ok to quickly move on to more important things.

> 95%, perhaps 98% or 99%, of the audience for this template will never publish anything to Sonatype in their entire lives

I am not too sure about that. If someone is using this template, they are starting a new build from scratch as opposed to git cloning someone else's build, like in the case of Coursera or Creative Scala. There are 75 forks to this repo. Maybe people who would fork things would have higher correlation, but 5% means fewer than four people on https://github.com/scala/scala-seed.g8/network/members will ever publish things to Sonatype in their lifetime.

**Comment by SethTisue** [comment]
>  95%, perhaps 98% or 99%, of the audience for this template will never publish anything to Sonatype in their entire lives

I stand by this claim. Open source maintainers are a tiny, tiny fraction of the overall community, and this template is intended for beginners, making the fraction even tinier.

I'd be happy to merge this without the Sonatype stuff. (I'd also stand aside if there was a consensus opinion that the Sonatype stuff should be there.)

**Comment by SethTisue** [comment]
possible compromise: how about including a one-line comment with a link to some other resource providing Sonatype publishing information?

**Comment by eed3si9n** [comment]
Deal.

**Pull request merged**
