### PR TITLE
Update to scala 3.1.0

### PR DESCRIPTION
**Pull request by gitting**
Updated to scala 3.1.0 and scalatest 3.2.10 while simplified in the spirit of scala3.g8

### CODE REVIEW

**Comment by SethTisue** [comment]
Might it be intentional that this repo stayed on Scala 2, with the Scala 3 templates be in separate repos?

In particular I'm wondering if I might have documentation that suggests doing `sbt new scala/scala-seed.g8` and assumes the result will be Scala 2.

(Not saying I know, just saying that we would need to be sure before merging this.)

**Comment by gitting** [comment]
> Might it be intentional that this repo stayed on Scala 2, with the Scala 3 templates be in separate repos?
> 
> In particular I'm wondering if I might have documentation that suggests doing `sbt new scala/scala-seed.g8` and assumes the result will be Scala 2.
> 
> (Not saying I know, just saying that we would need to be sure before merging this.)

I could not figure out such intent either, and finding myself wanting to have a scala3 template equipped with scalatest instead of junit I created this "hybrid" type instead. Offering it here in case many people find it useful. Not at all suggesting any urgency or infringing on any original intent.

In my clone I created a 3.1.x branch. Not sure how this repo might want to handle it, if at all.

**Comment by SethTisue** [comment]
I'm not sure who in the Scala Center could make a ruling here. (@sjrd?)

**Comment by gitting** [comment]
It could become its own branch - 3.1.x - similar to what's there now. Then a specific version could be requested as documented [here](https://www.scala-sbt.org/1.x/docs/sbt-new-and-Templates.html).
```
sbt new scala/scala-seed.g8 --branch 3.1.x
```

**Pull request closed without merging**
