### PR TITLE
Update ScalaTest to 3.1.1

### PR DESCRIPTION
**Pull request by danieletorelli**
This updates ScalaTest dependency to version 3.1.0

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]
LGTM. perhaps @cheeseng and @bvenners would like to take this opportunity to take a look that everything ScalaTest here is as it should be?

in particular, I'm wondering if we want to continue steering people towards `AnyFlatSpec`, or do the ScalaTest maintainers consider something else to be the best default for beginners?

(though, changing that could be a separate PR, I guess)

**Comment by cheeseng** [comment]
@SethTisue Sorry I just came back from a vacation for lunar calendar new year celebration.

I think @bvenners may prefer the following style: 

```
import org.scalatest._

class HelloSpec extends flatspec.AnyFlatSpec {...}
```

and similarly for Matchers too, @bvenners do you mind to confirm?

Cheers.

**Comment by eed3si9n** [comment]
> in particular, I'm wondering if we want to continue steering people towards `AnyFlatSpec`, or do the ScalaTest maintainers consider something else to be the best default for beginners?

FlatSpec was chosen in 2014 for Activator template (https://github.com/typesafehub/activator-minimal-scala/commit/9e10bb07e7d650414268e1ac000bd730f006b74c#diff-90aefc30fd337a54efbd814f8b0496d8), and I followed along in 2016.

However, I feel like we are in the midst of Renaissance, going back to the classical xUnit testing, with some property-based testing happening on the side. If we look at MUnit, Verify, and Minitest, these are all inspired by `FunSuite`. For beginners starting Scala now, I think going minimalist `FunSuite` is considered more modern rather than "it should" DSL.

**Comment by SethTisue** [comment]
or `AnyFunSuite`, perhaps? that's what I use personally and I feel (somewhat uncertainly) like it's what I see most in the wild, but I might be wrong; I'd defer to whatever you and Bill suggest

**Comment by SethTisue** [comment]
jinx :-)

**Comment by danieletorelli** [comment]
@SethTisue I can change it to `AnyFunSuite`, in case, but I guess it might be cleaner to open an issue to discuss those changes with all community members and to then tackle the results in a dedicated PR

**Pull request merged**
