### PR TITLE
Update scala and sbt version

### PR DESCRIPTION
**Pull request by aoiroaoino**

### CODE REVIEW

**Comment by SethTisue** [comment]
thank you!

**Comment by SethTisue** [comment]
@scala-steward the steward is enabled in this repo, but we've never received any PRs from the steward (and so it's left up to human PRs like this one). is it perhaps because it's a Giter8 template and the files are down inside `src/main`?

**Comment by aoiroaoino** [comment]
@SethTisue 
It also seems to update the internal files.
https://github.com/scala/scalatest-example.g8/pull/25/files

I'm not sure, but I think seems due to relating to a change in the default branch of the repository to 2.13.x after enabling stewards.

**Comment by SethTisue** [comment]
> I'm not sure, but I think seems due to relating to a change in the default branch of the repository to 2.13.x after enabling stewards.

ah — @scala-steward, does that seem plausible to your human keeper?

**Comment by fthomas** [comment]
> is it perhaps because it's a Giter8 template and the files are down inside src/main?

Most probably. Scala Steward can update Giter8 templates but only if the dependencies/plugins of the template are also dependencies/plugins of the build. See also this [FAQ](https://github.com/fthomas/scala-steward/blob/9633912cbec3b83f5d21a341092a8514bbe63f72/docs/faq.md#can-scala-steward-update-dependencies-in-giter8-templates-).

**Pull request merged**
