### PR TITLE
Bump to Scala 2.13.0

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by retronym** [comment]
Needs scalatest to be available before we can test + merge.

**Comment by SethTisue** [comment]
once merged, I can re-add the scala-seed.g8 mention to the 2.13.0 notes

**Comment by SethTisue** [comment]
ScalaTest is available now

but also, I just realized that this repo has separate 2.12.x and 2.13.x branches. so I'm closing this PR, I'll submit a 2.13.x replacement.

**Comment by SethTisue** [comment]
hmm, but I don't know how those branches are supposed to work, actually.

I don't have time to dig any deeper into this right now. @eed3si9n probably tonight isn't a good night to ask maybe you could advise us when you have time

**Comment by eed3si9n** [comment]
@SethTisue I got this.

**Comment by eed3si9n** [comment]
Giter8 can specify a branch, so there's just two branches now?
We can flip the default branch to 2.13.x once it's ready.

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/scala/scala-seed.g8/pull/34

**Pull request closed without merging**
