### PR TITLE
[2.12.x] Update Scalatest to 3.0.8

### PR DESCRIPTION
**Pull request by danieletorelli**
This updates Scalatest library from `3.0.5` to `3.0.8`.

### CODE REVIEW

**Comment by SethTisue** [comment]
@eed3si9n do you understand the Travis-CI failure?

**Comment by danieletorelli** [comment]
> @eed3si9n do you understand the Travis-CI failure?

@SethTisue it should be enough to merge https://github.com/scala/scala-seed.g8/pull/37 also in the target branch.

**Comment by SethTisue** [comment]
ah, okay, I've submitted a cherry-pick as #39

**Comment by danieletorelli** [comment]
Ok, I'll rebase this one once #39 will be merged then.

**Comment by SethTisue** [comment]
#39 is merged

**Comment by danieletorelli** [comment]
> #39 is merged

Rebased. Now is all passing.

**Pull request merged**
